### PR TITLE
Create DarkOnesk89

### PR DESCRIPTION
**Pull request by cg00001**
This corrects selected text.

### CODE REVIEW

**Comment by actionless** [comment]
> This corrects selected text.

if you want improve one of your older themes, please edit them instead of uploading it as a new one

**Comment by cg00001** [comment]
> > This corrects selected text.
> 
> if you want improve one of your older themes, please edit them instead of uploading it as a new one

Thanks, I'm planning to re-investigate all -besides the latest ones-, can't remember how to delete some though.
Should be as easy as editing and deleting all content?

**Comment by actionless** [comment]
yeah, you can just google "how to edit/delete things on github" 👍

**Comment by actionless** [comment]
https://github.com/themix-project/themix-gui/blob/master/colors/Contributed/DarkOnesk/DarkOnesk89

**Pull request closed without merging**
